export const FETCH_PAGE_TEXT = 'FETCH_PAGE_TEXT';
export const FETCH_PAGE_TEXT_START = 'FETCH_PAGE_TEXT_START';
export const FETCH_PAGE_TEXT_SUCCESS = 'FETCH_PAGE_TEXT_SUCCESS';
export const FETCH_PAGE_TEXT_FAIL = 'FETCH_PAGE_TEXT_FAIL';
export const SEND_ANALYTICS_EVENT = 'SEND_ANALYTICS_EVENT';
export const SEND_ANALYTICS_PAGE = 'SEND_ANALYTICS_PAGE';
